/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [3:0] io_sel,
    output reg [7:0] io_seg,
    output reg [7:0] io_seg2,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [1-1:0] M_start_button_out;
  reg [1-1:0] M_start_button_in;
  button_conditioner_2 start_button (
    .clk(clk),
    .in(M_start_button_in),
    .out(M_start_button_out)
  );
  wire [1-1:0] M_edge_start_button_out;
  reg [1-1:0] M_edge_start_button_in;
  edge_detector_3 edge_start_button (
    .clk(clk),
    .in(M_edge_start_button_in),
    .out(M_edge_start_button_out)
  );
  wire [1-1:0] M_p1_button1_out;
  reg [1-1:0] M_p1_button1_in;
  button_conditioner_2 p1_button1 (
    .clk(clk),
    .in(M_p1_button1_in),
    .out(M_p1_button1_out)
  );
  wire [1-1:0] M_edge_p1_button1_out;
  reg [1-1:0] M_edge_p1_button1_in;
  edge_detector_3 edge_p1_button1 (
    .clk(clk),
    .in(M_edge_p1_button1_in),
    .out(M_edge_p1_button1_out)
  );
  wire [1-1:0] M_p1_button2_out;
  reg [1-1:0] M_p1_button2_in;
  button_conditioner_2 p1_button2 (
    .clk(clk),
    .in(M_p1_button2_in),
    .out(M_p1_button2_out)
  );
  wire [1-1:0] M_edge_p1_button2_out;
  reg [1-1:0] M_edge_p1_button2_in;
  edge_detector_3 edge_p1_button2 (
    .clk(clk),
    .in(M_edge_p1_button2_in),
    .out(M_edge_p1_button2_out)
  );
  wire [1-1:0] M_p1_button3_out;
  reg [1-1:0] M_p1_button3_in;
  button_conditioner_2 p1_button3 (
    .clk(clk),
    .in(M_p1_button3_in),
    .out(M_p1_button3_out)
  );
  wire [1-1:0] M_edge_p1_button3_out;
  reg [1-1:0] M_edge_p1_button3_in;
  edge_detector_3 edge_p1_button3 (
    .clk(clk),
    .in(M_edge_p1_button3_in),
    .out(M_edge_p1_button3_out)
  );
  wire [1-1:0] M_p1_button4_out;
  reg [1-1:0] M_p1_button4_in;
  button_conditioner_2 p1_button4 (
    .clk(clk),
    .in(M_p1_button4_in),
    .out(M_p1_button4_out)
  );
  wire [1-1:0] M_edge_p1_button4_out;
  reg [1-1:0] M_edge_p1_button4_in;
  edge_detector_3 edge_p1_button4 (
    .clk(clk),
    .in(M_edge_p1_button4_in),
    .out(M_edge_p1_button4_out)
  );
  wire [1-1:0] M_edge_detector_slow_timer_out;
  reg [1-1:0] M_edge_detector_slow_timer_in;
  edge_detector_3 edge_detector_slow_timer (
    .clk(clk),
    .in(M_edge_detector_slow_timer_in),
    .out(M_edge_detector_slow_timer_out)
  );
  wire [1-1:0] M_slow_timer_value;
  counter_4 slow_timer (
    .clk(clk),
    .rst(rst),
    .value(M_slow_timer_value)
  );
  wire [32-1:0] M_random_num;
  reg [1-1:0] M_random_next;
  reg [32-1:0] M_random_seed;
  pn_gen_5 random (
    .clk(clk),
    .rst(rst),
    .next(M_random_next),
    .seed(M_random_seed),
    .num(M_random_num)
  );
  wire [6-1:0] M_game_fsm_alufn;
  wire [3-1:0] M_game_fsm_asel;
  wire [3-1:0] M_game_fsm_bsel;
  wire [2-1:0] M_game_fsm_wdsel;
  wire [4-1:0] M_game_fsm_wa;
  wire [4-1:0] M_game_fsm_ra;
  wire [4-1:0] M_game_fsm_rb;
  wire [1-1:0] M_game_fsm_we;
  wire [4-1:0] M_game_fsm_main_timer_sel;
  wire [8-1:0] M_game_fsm_main_timer_segs;
  wire [8-1:0] M_game_fsm_mini_timer_5_segs;
  wire [16-1:0] M_game_fsm_p1_led1;
  wire [16-1:0] M_game_fsm_p1_led2;
  wire [16-1:0] M_game_fsm_p1_led3;
  wire [16-1:0] M_game_fsm_p1_led4;
  wire [16-1:0] M_game_fsm_p2_led1;
  wire [16-1:0] M_game_fsm_p2_led2;
  wire [16-1:0] M_game_fsm_p2_led3;
  wire [16-1:0] M_game_fsm_p2_led4;
  reg [1-1:0] M_game_fsm_start_button;
  reg [1-1:0] M_game_fsm_p1_button1;
  reg [1-1:0] M_game_fsm_p1_button2;
  reg [1-1:0] M_game_fsm_p1_button3;
  reg [1-1:0] M_game_fsm_p1_button4;
  reg [1-1:0] M_game_fsm_dec;
  reg [16-1:0] M_game_fsm_rng16;
  fsm_auto_6 game_fsm (
    .clk(clk),
    .rst(rst),
    .start_button(M_game_fsm_start_button),
    .p1_button1(M_game_fsm_p1_button1),
    .p1_button2(M_game_fsm_p1_button2),
    .p1_button3(M_game_fsm_p1_button3),
    .p1_button4(M_game_fsm_p1_button4),
    .dec(M_game_fsm_dec),
    .rng16(M_game_fsm_rng16),
    .alufn(M_game_fsm_alufn),
    .asel(M_game_fsm_asel),
    .bsel(M_game_fsm_bsel),
    .wdsel(M_game_fsm_wdsel),
    .wa(M_game_fsm_wa),
    .ra(M_game_fsm_ra),
    .rb(M_game_fsm_rb),
    .we(M_game_fsm_we),
    .main_timer_sel(M_game_fsm_main_timer_sel),
    .main_timer_segs(M_game_fsm_main_timer_segs),
    .mini_timer_5_segs(M_game_fsm_mini_timer_5_segs),
    .p1_led1(M_game_fsm_p1_led1),
    .p1_led2(M_game_fsm_p1_led2),
    .p1_led3(M_game_fsm_p1_led3),
    .p1_led4(M_game_fsm_p1_led4),
    .p2_led1(M_game_fsm_p2_led1),
    .p2_led2(M_game_fsm_p2_led2),
    .p2_led3(M_game_fsm_p2_led3),
    .p2_led4(M_game_fsm_p2_led4)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    usb_tx = usb_rx;
    io_sel = 1'h0;
    io_seg = 1'h0;
    io_led = 24'h000000;
    M_random_seed = 128'h843233523a613966423b622562592c62;
    M_random_next = M_edge_detector_slow_timer_out;
    M_edge_detector_slow_timer_in = M_slow_timer_value;
    M_game_fsm_dec = M_edge_detector_slow_timer_out;
    M_game_fsm_rng16 = M_random_num[0+15-:16];
    io_led[8+6+0-:1] = M_game_fsm_p1_led1[0+0-:1];
    io_led[8+7+0-:1] = M_game_fsm_p1_led1[1+0-:1];
    io_led[16+0+0-:1] = M_game_fsm_p1_led1[2+0-:1];
    io_led[16+1+0-:1] = M_game_fsm_p1_led1[3+0-:1];
    io_led[0+0+0-:1] = M_game_fsm_p1_led2[0+0-:1];
    io_led[0+1+0-:1] = M_game_fsm_p1_led2[1+0-:1];
    io_led[0+2+0-:1] = M_game_fsm_p1_led2[2+0-:1];
    io_led[0+3+0-:1] = M_game_fsm_p1_led2[3+0-:1];
    io_led[8+0+0-:1] = M_game_fsm_p1_led3[0+0-:1];
    io_led[8+1+0-:1] = M_game_fsm_p1_led3[1+0-:1];
    io_led[8+2+0-:1] = M_game_fsm_p1_led3[2+0-:1];
    io_led[8+3+0-:1] = M_game_fsm_p1_led3[3+0-:1];
    io_led[16+4+0-:1] = M_game_fsm_p1_led4[0+0-:1];
    io_led[16+5+0-:1] = M_game_fsm_p1_led4[1+0-:1];
    io_led[16+6+0-:1] = M_game_fsm_p1_led4[2+0-:1];
    io_led[16+7+0-:1] = M_game_fsm_p1_led4[3+0-:1];
    M_start_button_in = ~io_dip[8+6+0-:1];
    M_edge_start_button_in = M_start_button_out;
    M_game_fsm_start_button = M_edge_start_button_out;
    M_p1_button1_in = io_dip[0+6+0-:1];
    M_p1_button2_in = io_dip[0+4+0-:1];
    M_p1_button3_in = io_dip[0+7+0-:1];
    M_p1_button4_in = io_dip[8+0+0-:1];
    M_edge_p1_button1_in = M_p1_button1_out;
    M_edge_p1_button2_in = M_p1_button2_out;
    M_edge_p1_button3_in = M_p1_button3_out;
    M_edge_p1_button4_in = M_p1_button4_out;
    M_game_fsm_p1_button1 = M_edge_p1_button1_out;
    M_game_fsm_p1_button2 = M_edge_p1_button2_out;
    M_game_fsm_p1_button3 = M_edge_p1_button3_out;
    M_game_fsm_p1_button4 = M_edge_p1_button4_out;
    io_seg = M_game_fsm_main_timer_segs;
    io_sel = M_game_fsm_main_timer_sel;
    io_seg2 = M_game_fsm_mini_timer_5_segs;
  end
endmodule
