/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module bin_to_digits_23 (
    input clk,
    input rst,
    input [7:0] in,
    output reg [7:0] digits
  );
  
  
  
  wire [8-1:0] M_operator_out;
  reg [8-1:0] M_operator_a;
  reg [8-1:0] M_operator_b;
  modulus_29 operator (
    .clk(clk),
    .rst(rst),
    .a(M_operator_a),
    .b(M_operator_b),
    .out(M_operator_out)
  );
  
  always @* begin
    M_operator_a = in;
    M_operator_b = 4'ha;
    digits[0+3-:4] = M_operator_out;
    digits[4+3-:4] = (in - M_operator_out) / 4'ha;
  end
endmodule
