/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     DIGITS = 2
*/
module multi_dec_ctr_19 (
    input clk,
    input rst,
    input dec,
    input reset0,
    input reset6,
    output reg [7:0] digits
  );
  
  localparam DIGITS = 2'h2;
  
  
  wire [1-1:0] M_dctr1_ovf;
  wire [4-1:0] M_dctr1_value;
  reg [1-1:0] M_dctr1_dec;
  reg [1-1:0] M_dctr1_reset0;
  reg [1-1:0] M_dctr1_reset6;
  decimal_counter_27 dctr1 (
    .clk(clk),
    .rst(rst),
    .dec(M_dctr1_dec),
    .reset0(M_dctr1_reset0),
    .reset6(M_dctr1_reset6),
    .ovf(M_dctr1_ovf),
    .value(M_dctr1_value)
  );
  wire [1-1:0] M_dctr2_ovf;
  wire [4-1:0] M_dctr2_value;
  reg [1-1:0] M_dctr2_dec;
  reg [1-1:0] M_dctr2_reset0;
  reg [1-1:0] M_dctr2_reset6;
  decimal_counter_28 dctr2 (
    .clk(clk),
    .rst(rst),
    .dec(M_dctr2_dec),
    .reset0(M_dctr2_reset0),
    .reset6(M_dctr2_reset6),
    .ovf(M_dctr2_ovf),
    .value(M_dctr2_value)
  );
  
  always @* begin
    M_dctr1_reset0 = reset0;
    M_dctr1_reset6 = 1'h0;
    M_dctr2_reset6 = reset6;
    M_dctr2_reset0 = 1'h0;
    digits[0+3-:4] = M_dctr1_value;
    digits[4+3-:4] = M_dctr2_value;
    M_dctr1_dec = dec;
    M_dctr2_dec = M_dctr1_ovf;
    if (M_dctr2_value == 1'h0 && M_dctr1_value == 1'h0) begin
      M_dctr1_dec = 1'h0;
      M_dctr2_dec = 1'h0;
    end
  end
endmodule
