# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.runs/synth_1/.Xil/Vivado-2380-LAPTOP-8BRI5POG/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a35tftg256-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/button_conditioner_2.v}
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/counter_15.v}
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/counter_16.v}
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/counter_4.v}
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/decimal_counter_18.v}
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/decimal_counter_19.v}
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/decimal_counter_20.v}
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/decimal_counter_5_11.v}
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/decoder_17.v}
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/edge_detector_14.v}
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/edge_detector_3.v}
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/fsm_auto_6.v}
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/look_up_table_13.v}
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/multi_dec_ctr_10.v}
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/multi_seven_seg_9.v}
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/pipeline_7.v}
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/pn_gen_5.v}
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/reset_conditioner_1.v}
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/seven_seg_12.v}
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/variable_counter_8.v}
      {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.srcs/sources_1/imports/verilog/au_top_0.v}
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList {{C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.runs/synth_1/.Xil/Vivado-2380-LAPTOP-8BRI5POG/realtime/au_top_0_synth.xdc}}
    rt::sdcChecksum
    set rt::top au_top_0
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/Cheng Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D Project/work/vivado/1D Project Computation Structures/1D Project Computation Structures.runs/synth_1/.Xil/Vivado-2380-LAPTOP-8BRI5POG/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
