/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module look_up_table_4 (
    input [3:0] randgen,
    output reg [3:0] led_Out
  );
  
  
  
  always @* begin
    
    case (randgen)
      1'h1: begin
        led_Out = 1'h1;
      end
      4'ha: begin
        led_Out = 1'h1;
      end
      7'h64: begin
        led_Out = 1'h1;
      end
      10'h3e8: begin
        led_Out = 1'h1;
      end
      4'hb: begin
        led_Out = 4'hb;
      end
      7'h65: begin
        led_Out = 4'hb;
      end
      10'h3e9: begin
        led_Out = 4'hb;
      end
      11'h44c: begin
        led_Out = 4'hb;
      end
      7'h6f: begin
        led_Out = 7'h6f;
      end
      10'h3f3: begin
        led_Out = 7'h6f;
      end
      11'h44d: begin
        led_Out = 7'h6f;
      end
      11'h456: begin
        led_Out = 7'h6f;
      end
      11'h457: begin
        led_Out = 11'h457;
      end
      7'h6e: begin
        led_Out = 11'h457;
      end
      10'h3f2: begin
        led_Out = 11'h457;
      end
      1'h0: begin
        led_Out = 11'h457;
      end
      default: begin
        led_Out = 1'h0;
      end
    endcase
  end
endmodule
