set projDir "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/vivado"
set projName "1D Project Computation Structures"
set topName top
set device xc7a35tftg256-1
if {[file exists "$projDir/$projName"]} { file delete -force "$projDir/$projName" }
create_project $projName "$projDir/$projName" -part $device
set_property design_mode RTL [get_filesets sources_1]
set verilogSources [list "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/au_top_0.v" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/reset_conditioner_1.v" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/button_conditioner_2.v" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/edge_detector_3.v" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/counter_4.v" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/pn_gen_5.v" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/fsm_auto_6.v" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/pipeline_7.v" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/variable_counter_8.v" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/multi_seven_seg_9.v" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/multi_dec_ctr_10.v" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/decimal_counter_5_11.v" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/seven_seg_12.v" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/look_up_table_13.v" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/edge_detector_14.v" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/counter_15.v" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/counter_16.v" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/decoder_17.v" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/decimal_counter_18.v" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/decimal_counter_19.v" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/verilog/decimal_counter_20.v" ]
import_files -fileset [get_filesets sources_1] -force -norecurse $verilogSources
set xdcSources [list "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/constraint/io.xdc" "C:/Users/Cheng\ Xin/Documents/Alchitry/50.002-Computation-Structures-1D-Project/Game/1D\ Project/work/constraint/alchitry.xdc" "D:/Program\ Files/Alchitry\ Labs/library/components/au.xdc" ]
read_xdc $xdcSources
set_property STEPS.WRITE_BITSTREAM.ARGS.BIN_FILE true [get_runs impl_1]
update_compile_order -fileset sources_1
launch_runs -runs synth_1 -jobs 8
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1
